version: '3.8'

services:
  aiquiz:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    ports:
      - "${HOST_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aiquiz-network

networks:
  aiquiz-network:
    driver: bridge
