name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        build-args: |
          VITE_TMDB_API_KEY=${{ secrets.VITE_TMDB_API_KEY }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup Ansible
      run: |
        pip install ansible

    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy with Ansible
      run: |
        cd ansible
        # Update inventory with actual values
        sed -i "s/YOUR_SERVER_IP/${{ secrets.DEPLOY_HOST }}/g" inventory.yml
        sed -i "s/your-username/${{ github.repository_owner }}/g" inventory.yml
        sed -i "s/your-domain.com/${{ secrets.DEPLOY_DOMAIN || secrets.DEPLOY_HOST }}/g" inventory.yml
        
        # Run the playbook
        ansible-playbook -i inventory.yml playbook.yml \
          -e "github_repository=${{ github.repository }}" \
          -e "ansible_user=${{ secrets.DEPLOY_USER }}" \
          --private-key ~/.ssh/id_rsa
